version: '3'

services:

  postgres:
    image: postgis/postgis:14-3.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./docker-compose.env
    expose:
      - "5432"

  web:
      build:
        context: ../
        dockerfile: ./deploy/Dockerfile
      env_file:
        - ./docker-compose.env
      ports:
        - 8000:8000

volumes:
  postgres_data:
  postgres_backups:
