# Generated by Django 4.1.4 on 2022-12-12 05:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "postal_code",
                    models.PositiveIntegerField(verbose_name="Почтовый индекс"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "federal_district",
                    models.CharField(max_length=100, verbose_name="Федеральный район"),
                ),
                (
                    "region_type",
                    models.CharField(max_length=20, verbose_name="Тип региона"),
                ),
                ("region", models.CharField(max_length=100, verbose_name="Региона")),
                (
                    "area_type",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Тип области"
                    ),
                ),
                (
                    "area",
                    models.CharField(max_length=100, null=True, verbose_name="Область"),
                ),
                (
                    "city_type",
                    models.CharField(max_length=100, verbose_name="Тип города"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "settlement_type",
                    models.CharField(max_length=100, verbose_name="Тип поселка"),
                ),
                (
                    "settlement",
                    models.CharField(max_length=100, verbose_name="Поселок"),
                ),
                (
                    "lоcation",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="Первым значением идет долгота longitude, а вторым значением широта latitude",
                        srid=4326,
                        verbose_name="Геопозиция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
    ]
